ALL: lib

BASEDIR    =    ${SESKADIR}
LOCDIR     = 	${BASEDIR}/src/preProcessing
DIRS       =	

SOURCEC    =	AsymShapeFunc.C \
		BackgroundMesh.C \
		BasisPolyAsym.C \
		BasisPolynomSets.C \
		BasisPolyOrtho.C \
		BasisPolyRegular.C \
		CardiacFibreGenerator.C \
		EFGShapeFunc.C \
		FEMDiscretising.C \
		GaussPoint.C \
		GaussPointSets.C \
		IntegrationPoint.C \
		MaxEntDiscretising.C \
		MaxEntShapeFunc.C \
		MeshlessApproximation.C \
		MicroSpace.C \
		MLSDiscretising.C \
		MLSGaussIntegral.C \
		MLSPtcleIntegral.C \
		MLSShapeFuncSet.C \
		OrthoShapeFunc.C \
		Particle.C \
		ParticleDistribution.C \
		PrismaticWindowFunction.C \
		PrismaticWindowFunctionSet.C \
		RKPMShapeFunc.C \
		ShepardShapeFunc.C \
		SphericalWindowFunctionSet.C \
		WindowFuncAsym.C
#SOURCEC    =    BackgroundMesh.C

SOURCEF    =

SOURCEH    =	AsymShapeFunc.h \
		BackgroundMesh.h \
		BasisPolyAsym.h \
		BasisPolynom.h \
		BasisPolyOrtho.h \
		BasisPolyRegular.h \
		BasisPolynomSets.h \
		CardiacFibreGenerator.h \
		CustomSpline.h \
		EFGShapeFunc.h \
		FEMDiscretising.h \
		GaussPoint.h \
		GaussPointSets.h \
		IntegrationPoint.h \
		MaxEntDiscretising.h \
		MaxEntShapeFunc.h \
		MeshlessApproximation.h \
		MicroGaussPoint.h \
		MicroSpace.h \
		MLSDiscretising.h \
		MLSGaussIntegral.h \
		MLSPtcleIntegral.h \
		MLSShapeFuncSet.h \
		OrthoShapeFunc.h \
		Particle.h \
		ParticleDistribution.h \
		PrismaticWindowFunction.h \
		PrismaticWindowFunctionSet.h \
		RKPMShapeFunc.h \
		ShapefunctionSet.h \
		ShepardShapeFunc.h \
		SphericalWindowFunctionSet.h \
		WindowFuncAsym.h \
		WindowFunctionSet.h

OBJSC      =	AsymShapeFunc.o \
		BackgroundMesh.o \
		BasisPolyAsym.o \
		BasisPolynomSets.o \
		BasisPolyOrtho.o \
		BasisPolyRegular.o \
		CardiacFibreGenerator.o \
		EFGShapeFunc.o \
		FEMDiscretising.o \
		GaussPoint.o \
		GaussPointSets.o \
		IntegrationPoint.o \
		MaxEntDiscretising.o \
		MaxEntShapeFunc.o \
		MeshlessApproximation.o \
		MicroSpace.o \
		MLSDiscretising.o \
		MLSGaussIntegral.o \
		MLSPtcleIntegral.o \
		MLSShapeFuncSet.o \
		OrthoShapeFunc.o \
		Particle.o \
		ParticleDistribution.o \
		PrismaticWindowFunction.o \
		PrismaticWindowFunctionSet.o \
		RKPMShapeFunc.o \
		ShepardShapeFunc.o \
		SphericalWindowFunctionSet.o \
		WindowFuncAsym.o
#OBJSC      =    BackgroundMesh.o

OBJSF      =
LIBBASE    = libseskaPreproc
LIBDIR     = ${BASEDIR}/lib
PROG       = seska



include  ${BASEDIR}/config/variables
