
ALL: lib

BASEDIR    = ${SESKADIR}
LOCDIR     = ${BASEDIR}/src/preProcessing/FEMGeometry/
DIRS       =

SOURCEC    =	FEMElement.C \
		FEMGeometry.C \
		LineElementTemplates.C \
		SurfaceElementTemplates.C \
		VolumeElementTemplates.C
#SOURCEC    =	FEMGeometry.C

SOURCEF    =
SOURCEH    = 	ElementTemplate.h \
		FEMElement.h \
		FEMGeometry.h \
		LineElementTemplates.h \
		SurfaceElementTemplates.h \
		VolumeElementTemplates.h

OBJSC      =	FEMElement.o \
		FEMGeometry.o \
		LineElementTemplates.o \
		SurfaceElementTemplates.o \
		VolumeElementTemplates.o
#OBJSC      =	FEMGeometry.o

OBJSF      =
LIBBASE    = libseskaFEMGeo


include  ${BASEDIR}/config/variables
